# WeatherAPI - autentisering via Query Parameter
weather.api.key=65336450a5d547deade83306262805
weather.api.base-url=http://api.weatherapi.com/v1
weather.api.timeout=5000
geoapify.api.key=d874510b36904cc3b5aa16e203d1f576
geoapify.api.base-url=https://api.geoapify.com
geoapify.api.timeout=5000
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always