# WeatherAPI - autentisering via Query Parameter
weather.api.key=65336450a5d547deade83306262805
weather.api.base-url=http://api.weatherapi.com/v1
weather.api.timeout=5000
geoapify.api.key=d874510b36904cc3b5aa16e203d1f576
geoapify.api.base-url=https://api.geoapify.com
geoapify.api.timeout=5000
management.endpoints.web.exposure.include=health,circuitbreakers
management.endpoint.health.show-details=always

resilience4j.circuitbreaker.circuit-breaker-aspect-order=1
resilience4j.retry.retry-aspect-order=2
management.health.circuitbreakers.enabled=true

resilience4j.circuitbreaker.instances.geoapify.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.geoapify.sliding-window-size=10
resilience4j.circuitbreaker.instances.geoapify.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.geoapify.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.geoapify.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.geoapify.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.geoapify.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.geoapify.register-health-indicator=true

resilience4j.retry.instances.geoapify.max-attempts=3
resilience4j.retry.instances.geoapify.wait-duration=1s
resilience4j.retry.instances.geoapify.enable-exponential-backoff=true
resilience4j.retry.instances.geoapify.exponential-backoff-multiplier=2

resilience4j.circuitbreaker.instances.weather.sliding-window-size=10
resilience4j.circuitbreaker.instances.weather.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.weather.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.weather.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.weather.register-health-indicator=true

resilience4j.retry.instances.weather.max-attempts=3
resilience4j.retry.instances.weather.wait-duration=1s
resilience4j.retry.instances.weather.enable-exponential-backoff=true
resilience4j.retry.instances.weather.exponential-backoff-multiplier=2

